// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msgyqamerjlvxawdekkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zZ3lxYW1lcmpsdnhhd2Rla2tuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNjY3MzIsImV4cCI6MjA3MTg0MjczMn0.dA6y2v-OG6nZbS9u3hLk6yAImhXKNeh_Mjf-e3kUn8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});